import type { MenuItem } from "../order/orderTypes";

export const menuItems: MenuItem[] = [
  {
    id: "spicy-chicken-medium",
    category: "food",
    name: "매콤닭강정",
    option: "중",
    price: 15000,
    note: "수제 피클 포함",
    sortOrder: 10,
  },
  {
    id: "spicy-chicken-large",
    category: "food",
    name: "매콤닭강정",
    option: "대",
    price: 20000,
    note: "수제 피클 포함",
    sortOrder: 11,
  },
  {
    id: "mayo-chicken-medium",
    category: "food",
    name: "청양마요닭강정",
    option: "중",
    price: 15000,
    note: "수제 피클 포함",
    sortOrder: 20,
  },
  {
    id: "mayo-chicken-large",
    category: "food",
    name: "청양마요닭강정",
    option: "대",
    price: 20000,
    note: "수제 피클 포함",
    sortOrder: 21,
  },
  { id: "crispy-hot-wing", category: "food", name: "크리스피핫윙", option: "7조각", price: 12000, sortOrder: 30 },
  { id: "fries", category: "food", name: "감자튀김", option: "기본", price: 15000, sortOrder: 40 },
  { id: "shrimp-croquette", category: "food", name: "왕새우튀김 + 고로케", option: "기본", price: 18000, sortOrder: 50 },
  { id: "bibim-mandu", category: "food", name: "비빔야끼만두", option: "기본", price: 15000, sortOrder: 60 },
  { id: "dried-pollack", category: "food", name: "먹태한마리", option: "기본", price: 15000, sortOrder: 70 },
  { id: "butter-squid", category: "food", name: "오징어버터구이", option: "기본", price: 15000, sortOrder: 80 },
  { id: "nogari", category: "food", name: "대구노가리", option: "기본", price: 12000, sortOrder: 90 },
  { id: "boneless-chicken-feet", category: "food", name: "석쇠구이무뼈닭발", option: "기본", price: 15000, sortOrder: 100 },
  { id: "soju", category: "drink", name: "소주", option: "기본", price: 5000, sortOrder: 200 },
  { id: "beer", category: "drink", name: "맥주", option: "기본", price: 5000, sortOrder: 210 },
  { id: "soft-drink", category: "drink", name: "음료수", option: "기본", price: 2000, sortOrder: 220 },
];
